language: python
python:
  - 2.6
  - 2.7
env:
  - DJANGO_VERSION=1.3.5
  - DJANGO_VERSION=1.4.3
  - DJANGO_VERSION=1.5b2
install:
  - pip install -q https://github.com/django/django/archive/${DJANGO}.zip#egg=django
  - python setup.py -q install
script: python setup.py test
branches:
  only:
    - dev